(part "SN74AVC2T245RSWR"
    (packageRef "RSW_RPUQFNN10_")
    (interface
        (port "1" (symbPinId 1) (portName "DIR2") (portType INOUT))
        (port "2" (symbPinId 2) (portName "%OE2%") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType GROUND))
        (port "4" (symbPinId 4) (portName "B2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "B1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VCCB") (portType POWER))
        (port "7" (symbPinId 7) (portName "VCCA") (portType POWER))
        (port "8" (symbPinId 8) (portName "A1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "A2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "DIR1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-SN74AVC2T245RSWR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/SN74AVC2T245RSWR?qs=59Rn2Bt6jP10ddXtSUJOPw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "SN74AVC2T245RSWR")
    (property "Description" "Dual-Bit, 2-DIR pin Dual-Supply Bus Transceiver w/ Configurable Voltage Translation, 3-State Output")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/sn74avc2t245.pdf")
    (property "symbolName1" "SN74AVC2T245RSWR")
)
